### ISSUE TITLE
["To-do" Feature] Deletion of task does not redirect to index

### ISSUE THREAD

**Issue by jiayeerawr** [notice-us-senpai/KouhaiDash#2]
![screenshot from 2016-05-20 23-43-08](https://cloud.githubusercontent.com/assets/14961285/15433369/ab5688b2-1ee4-11e6-8209-f1289a95d092.png)

**Comment by jiayeerawr** [comment]
From: 
format.html { redirect_to task_url, notice: 'Task was successfully destroyed.' }

To: 
format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }

Will be included in the next commit by myself

**Comment by jiayeerawr** [comment]
Not sure if that commit by myself was rolled back because I did not want to build upon @leeyimin 's commit, so that there will be no confusion. Will need @leeyimin to check this out.

**Comment by leeyimin** [comment]
Fixed in Task branch by and redirected to group_category_tasks_path(@group, @category)
