### ISSUE TITLE
Cannot login or logout

### ISSUE THREAD

**Issue by leeyimin** [notice-us-senpai/KouhaiDash#21]
Trying to logout:
![trouble](https://cloud.githubusercontent.com/assets/6365864/16087862/2a13021c-3357-11e6-888c-99ffe6b37dd9.png)
Same problem occurs on the line with update_attribute when logging in.
However, logging in and logging out is possible after commenting out these lines in user.rb
```
mount_uploader :image, ImageUploader
validates_processing_of :image
```

**Comment by jiayeerawr** [comment]
mount_uploader :image, ImageUploader
validates_processing_of :image

is tied to the carrierwave gem. Did you run "bundle install"? 
If it still fails after "bundle install", maybe "sudo gem install carrierwave" would be favourable... although I do not understand the difference

[Difference between bundle install and gem install](http://stackoverflow.com/questions/6162047/difference-between-bundle-and-gem-install)

**Comment by jiayeerawr** [comment]
Production is deploying 02068cf from master branch at https://kouhaidash.herokuapp.com/

Will do my best to pull your changes in. The last time I did it, it crashed because your feature was not finished that time, wasn't it T_T

**Comment by leeyimin** [comment]
Turns out it was bcos picture was not renamed to image in User Model in my db. Sorry for the misunderstanding 😂

**Comment by jiayeerawr** [comment]
I got the same error too...

but it wasn't because of the schema. I had to bundle install or something like that, because I did a db:migrate:reset before.
