### ISSUE TITLE
Problem with Downloading contacts as csv

### ISSUE THREAD

**Issue by leeyimin** [notice-us-senpai/KouhaiDash#30]
![kouhaidash-contacts-2016-06-25 read-only - excel 26_6_2016 2_06_57 am](https://cloud.githubusercontent.com/assets/6365864/16358339/ba95838a-3b42-11e6-98f2-6fcfac4944ae.png)
Tried downloading contacts on deploy and found this.

**Comment by jiayeerawr** [comment]
This is terrible. I have removed this feature because it fails even though there was no change to the code.
