### ISSUE TITLE
Display pictures disappeared

### ISSUE THREAD

**Issue by leeyimin** [notice-us-senpai/KouhaiDash#31]
![bug](https://cloud.githubusercontent.com/assets/6365864/16362298/f19a8b5a-3bdd-11e6-8d3c-76133b553545.png)

Display pictures of 2 users are gone on deploy

**Comment by jiayeerawr** [comment]
That sucks. However, there is no problem if I upload my picture client -> server.

Did you encounter this problem by inserting the file yourself and not with the uploader in the Settings page?

**Comment by leeyimin** [comment]
Nope. Uploaded from settings as well. But they disappear after a while. It happened to my yimin account just today again.

**Comment by jiayeerawr** [comment]
@leeyimin we are screwed

Check out the link below: 

[](http://stackoverflow.com/questions/29780651/uploaded-images-appear-to-save-then-disappear-later)
