### ISSUE TITLE
Use of Period in Username

### ISSUE THREAD

**Issue by leeyimin** [notice-us-senpai/KouhaiDash#34]
https://kouhaidash.herokuapp.com/users/kattie.kshlerin
cannot be accessed as kshlerin is read as format ( taken as like html, js)

**Comment by jiayeerawr** [comment]
We should proceed with blocking such problematic characters.

**Comment by leeyimin** [comment]
fixed by adding format validator, only letters, digits, '-' and '_' allowed.
